name: skidl2
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - icu
  - ipython
  - jupyter
  - matplotlib
  - ngspice-lib
  - ngspice-exe
  - ngspice
  - numpy
  - pytest
  - pandas
  - wxpython=4.1.1
  - pip
  - scipy
  - python=3.10
  - pip:
    - pyspice
    - pykicad
    - skidl>=1.1.0
    - rkm-codes